### ISSUE TITLE
Run with the Erro

### ISSUE THREAD

**Issue by lrnrzg** [daimajia/AnimeTaste#27]
10-26 09:24:46.480 14558-14609/com.zhan_dui.animetaste E/ShareSDK platform config result ==>>: SNS configuration is empty
10-26 09:24:46.498 14558-14609/com.zhan_dui.animetaste W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-26 09:24:46.500 14558-14607/com.zhan_dui.animetaste W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.protocol.RequestUserAgent.process(RequestUserAgent.java:83)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.protocol.BasicHttpProcessor.process(BasicHttpProcessor.java:295)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.protocol.HttpRequestExecutor.preProcess(HttpRequestExecutor.java:165)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:418)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.network.i.a(Unknown Source)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.network.i.a(Unknown Source)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.network.i.a(Unknown Source)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.statistics.a.f(Unknown Source)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.p.a(Unknown Source)
10-26 09:24:47.157 14558-14609/com.zhan_dui.animetaste W/System.err:     at cn.sharesdk.framework.q.run(Unknown Source)
10-26 09:24:47.190 14558-14621/com.zhan_dui.animetaste W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.activeandroid.TableInfo.getTableName()' on a null object reference
10-26 09:24:47.190 14558-14607/com.zhan_dui.animetaste W/System: ClassLoader referenced unknown path: /system/framework/tcmclient.jar
10-26 09:24:47.191 14558-14621/com.zhan_dui.animetaste W/System.err:     at com.activeandroid.Cache.getTableName(Unknown Source)
10-26 09:24:47.191 14558-14621/com.zhan_dui.animetaste W/System.err:     at com.activeandroid.query.From.toSql(Unknown Source)
10-26 09:24:47.191 14558-14621/com.zhan_dui.animetaste W/System.err:     at com.activeandroid.query.From.execute(Unknown Source)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at com.zhan_dui.animetaste.LoadActivity$PrepareTask.doInBackground(LoadActivity.java:209)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at com.zhan_dui.animetaste.LoadActivity$PrepareTask.doInBackground(LoadActivity.java:184)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
10-26 09:24:47.192 14558-14621/com.zhan_dui.animetaste W/System.err:     at java.lang.Thread.run(Thread.java:818)
10-26 09:24:47.193 14558-14621/com.zhan_dui.animetaste E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                         Process: com.zhan_dui.animetaste, PID: 14558
                                                                         java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
                                                                             at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:915)
                                                                             at android.database.sqlite.SQLiteSession.setTransactionSuccessful(SQLiteSession.java:371)
                                                                             at android.database.sqlite.SQLiteDatabase.setTransactionSuccessful(SQLiteDatabase.java:540)
                                                                             at com.activeandroid.ActiveAndroid.setTransactionSuccessful(Unknown Source)
                                                                             at com.zhan_dui.animetaste.LoadActivity$PrepareTask.doInBackground(LoadActivity.java:247)
                                                                             at com.zhan_dui.animetaste.LoadActivity$PrepareTask.doInBackground(LoadActivity.java:184)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                             at java.lang.Thread.run(Thread.java:818) #

**Comment by BigFaceCatMhc** [comment]
我运行之后也遇到类似问题，不知道是什么原因
